### ISSUE TITLE
Question: Why does each quote need a link to the script?

### ISSUE THREAD

**Issue by caraya** [Blogger-Peer-Review/quotebacks#17]
I'm trying to create a WordPress plugin to make installing backquotes easier but find out that I remove the link to the script on the individual quotes, only the first quoteback gets properly styled, any subsequent one misses the styles and gets the default style for blockquotes. It appears that if the first quotation on a page has the script (regardless of where it points to local or remote) the other quotations will work fine

**Comment by devilgate** [comment]
I'm glad you've raised this, because I'm having exactly the same problem. Not with WordPress, but with a static site. I'd have a go at fixing it, but my JavaScript isn't up to it. As far as I can tell, it looks like it should process everything with the `quoteback` class, but clearly that's not happening.

**Comment by tobyshorin** [comment]
We've got a working fix for this and will deploy a new version soon!

**Comment by caraya** [comment]
@tobyshorin Thanks for the update

**Comment by caraya** [comment]
@tobyshorin  Thanks for the information. 

I copied quoteback.js from the v1.0.3 tag into my plugin and it works as intended.
